dist: trusty
sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '9'
  - '8'
notifications:
  email: false
before_install:
  - npm i -g npm@latest greenkeeper-lockfile
install:
  - npm install # npm ci is not compatible with greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper.*$/
